version: '3'

networks:
  back-tier:

services:
  redis:
    hostname: "redis"
    image: redis:alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    restart: always
    networks:
      - back-tier
  app:
    hostname: "app"
    image: driael/364c7fd23d7
    container_name: projet_container
    environment:
      REDIS_HOST: redis
    ports:
      - "3000:3000"
    restart: on-failure
    build: .
    depends_on:
      - redis

    networks:
      - back-tier
