version: "3"
services:
    redis:
        image: redis
        container_name: cache
        expose:
          - 6379
    userapi:
        image: node:16
        restart: always
        ports:
            - "5000:5000"
        volumes:
            - ./userapi:/userapi
        working_dir: /userapi
        command: npm run start