version: '3'
services:
  redis:
    image: redis
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD","redis-cli",'ping']
      interval: 5s
      timeout: 20s
      retries: 5
  web:
    build: .
    ports:
      - "5000:8080"
    volumes:
      - myvolume:/data
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    restart: on-failure
    depends_on:
      redis:
        condition: service_healthy
    links:
      - redis
        
volumes:
  myvolume: